#!/bin/bash
#Capture root app directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../" && pwd )"

function error {
	echo "Error Building, will now halt"
	exit 1
}

#Include dependancies such as jUnit and our code
export CLASSPATH="$DIR/deps/junit/*:$DIR/deps/neo4j/*:$DIR/deps/jsap/*:$DIR/src"

#compile project classes
find "$DIR/src/" -name "*.java" | xargs javac -Xlint:deprecation || error
