#!/bin/bash
#Capture root app directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../" && pwd )"

source $DIR/util/build

#run test classes through JUnit,       Strip filename up-to /src/, get classname  replace / with ".", Tell junit to run that class
find "$DIR/src/test" -name "*.class" | sed "s:\(.*\)/src/\(.*\)\.class:\2:" | tr "/" "." | xargs java org.junit.runner.JUnitCore 
